// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "",
  aws_cognito_identity_pool_id: "",
  aws_cognito_region: "",
  aws_user_pools_id: "",
  aws_user_pools_web_client_id: "",
  aws_mobile_analytics_app_id: "",
  aws_mobile_analytics_app_region: ""
};

export default awsmobile;
